MODEL:
  VID:
    RPN:
      # 300 rois for selsa
      REF_POST_NMS_TOP_N: 75
    METHOD: "mamba"
    MAMBA:
      SHUFFLE_TEST: True
      PIX_MEM:
        ENABLE: False
      INS_MEM:
        ENABLE: True
  META_ARCHITECTURE: "GeneralizedRCNNMAMBA"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  BACKBONE:
    CONV_BODY: "R-101-C4"
  ROI_BOX_HEAD:
    FEATURE_EXTRACTOR: "MAMBAFeatureExtractor"
    PREDICTOR: "FPNPredictor"
DATASETS:
  TRAIN: ("DET_train_30classes", "VID_train_15frames")
  TEST: ("VID_val_videos",)
TEST:
  IMS_PER_BATCH: 4
  DETECTIONS_PER_IMG: 300
OUTPUT_DIR: "training_dir/MAMBA/vid_R_101_C4_INS_SSD_AUG_0x"
INPUT:
  ENABLE_SSD_AUG: True
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (40000, )
  MAX_ITER: 60000
  IMS_PER_BATCH: 4
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 20000
